### ISSUE TITLE
File open

### ISSUE THREAD

**Issue by allardjo** [Hmerritt/smartlister#4]
**No coding expert here!**

First of all, thanks for this superb File browser ! I was looking for that exact type of file browser with thumbnails and stuff. It even has extra features like uploading which is super nice.

I was just wondering one thing : when you click on a file, it opens in another window with the name of the file itself (let's say test.jpg) instead of hostname(website)/test.jpg hence resulting in an error. I tried browsing around in settings.php, useful.php, index.php and can't seem to find the exact thing I need to modify to get that working. Just let me know if it's something pretty basic, the script in my case is installed in a subfolder of my website (blah.website.com), so basically the file should open with blah.website.com/file and it's not.

Cheers mate.

**Comment by hmerritt** [comment]
### Hey there

I have looked into this issue and I think I have found the problem and fixed it (just re-clone the master branch to update).

However, I was not able to re-create this bug myself so I don't know if the fix will work as expected. If not; be sure to add another comment and I will be happy to look into it further.

**Comment by allardjo** [comment]
It's definitely working, though it adds a second "/" between the hostname and the file itself (example.com//file.jpg)

Is it possible to have the choice of opening the link in the same window ? Or this is a browser property ?

Anyway thanks for the super quick fix !!

**Comment by hmerritt** [comment]
I have fixed the double "/" issue.

As for the other question; I like the idea but It would not really be feasible to add an option of opening a link in the same window.

Since I have fixed the main issue, I am going to close this one. If you have any other suggestions feel free to just open another issue.
